fix: salesforce kamelet file for update operation
apache/camel-kafka-connector pull request #1502
Opened 2023-01-17 18:27 UTC by Matheusafonsouza

Fixing the kamelet file for salesforce update sink. Today this file only accepts the fields `sObjectId` and `sObjectName` by properties.

Even if i use the header-to-property mapper does not work. So i made some modifications to use the sink dynamically.

2023-01-17 18:34 UTC, oscerd requested changes
Eventually this needs to be done in camel-kamelets repository and then re-used in this project. Thanks

2023-01-17 19:20 UTC, Matheusafonsouza commented
@oscerd i created the PR on camel-kamelets for this
https://github.com/apache/camel-kamelets/pull/1240/files

2023-01-18 19:29 UTC, Matheusafonsouza commented
hey @oscerd, i saw that the PR at camel-kamelets was merged, what can i do in this repo now to proceed?

2023-01-18 19:50 UTC, Matheusafonsouza commented
there`s a release schedule? i saw something about in a PR or Issue

2023-01-19 09:21 UTC, oscerd commented
No ETA for 3.21.0 release at the moment, we still need to release 3.20.x

2023-01-19 12:08 UTC, Matheusafonsouza commented
Okay, i'll be waiting

2023-01-26 10:06 UTC, valdar commented
@Matheusafonsouza tnx a lot for the contribution! Since the PR to camel kamelets has been merged, are you ok with closing this one?

2023-01-26 14:23 UTC, closed without merging